apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-node
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:be99inner/devops-argocd-practice.git
    targetRevision: HEAD
    path: controller/karpenter-node
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
